/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.est.views;
import com.est.ctrl.registroD;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.Authenticator;
import java.net.MalformedURLException;
import java.net.PasswordAuthentication;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author m
 */
public class viewEntrada extends javax.swing.JDialog {
        int opcion;
        registroD registro = new registroD();
        private final String IP;        
        private final String pathFotos = "data\\";
        private final String usuario = "admin";
        private final String contra = "admin";
        private final String rutaF;
        private final String hrEntrada;
        boolean hayConexion;
    /**
     * Creates new form viewAgregarPensionado
     */
    private String getFechaActual() {
        Date ahora = new Date();
        SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return formateador.format(ahora);
    }  
    public viewEntrada(javax.swing.JFrame parent, boolean modal, String IP, boolean hayConexion) {        
        super(parent, modal);        
        this.IP = IP;
        initComponents();
        this.hrEntrada = getFechaActual();
        this.rutaF = "E"+hrEntrada.replace(" ","").replace(":","_").replace("-","");
        System.out.println("**************************"+rutaF);
        if(hayConexion){
            guardarFoto(rutaF, this.IP);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCamioneta = new javax.swing.JButton();
        btnAuto = new javax.swing.JButton();
        btnHotel1 = new javax.swing.JButton();
        btnHotel2 = new javax.swing.JButton();
        btnPensionado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(250, 200, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Entrada de Automovil");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signin_-32.png"))); // NOI18N

        btnCamioneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SUV-128.png"))); // NOI18N
        btnCamioneta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCamioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamionetaActionPerformed(evt);
            }
        });

        btnAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sedan-128.png"))); // NOI18N
        btnAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoActionPerformed(evt);
            }
        });

        btnHotel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHotel1.setText("La Alhondiga");
        btnHotel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHotel1.setMaximumSize(new java.awt.Dimension(161, 85));
        btnHotel1.setMinimumSize(new java.awt.Dimension(161, 85));
        btnHotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotel1ActionPerformed(evt);
            }
        });

        btnHotel2.setText("Puebla de Antaño");
        btnHotel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHotel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotel2ActionPerformed(evt);
            }
        });

        btnPensionado.setText("PENSIONADO");
        btnPensionado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPensionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPensionadoActionPerformed(evt);
            }
        });

        jLabel3.setText("Auto");

        jLabel4.setText("Camioneta");

        jLabel5.setText("Hotel 1");

        jLabel6.setText("Hotel 2");

        jLabel7.setText("Pensionado");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error-32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel5)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel6)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCamioneta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPensionado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCamioneta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPensionado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoActionPerformed
        // TODO add your handling code here:
        String folio = registro.getFolio();
            registro.setEntrada(folio,"Automovil", true, false,1,this.hrEntrada);
        this.opcion = 1;
        this.setVisible(false);
    }//GEN-LAST:event_btnAutoActionPerformed

    private void guardarFoto(String nombreArchivo, String direccionIP ){        
        URL nurl = null;
        BufferedImage imagen = null;
        try {
            nurl = new URL(direccionIP);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        Authenticator au = new Authenticator() {@Override
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication (usuario, contra.toCharArray());
        }};
        Authenticator.setDefault(au);
        try {
            imagen = ImageIO.read(nurl);
        } catch (IOException ex) {
            //Logger.getLogger(PanelVideoCam.class.getName()).log(Level.SEVERE, null, ex);
            //ex.printStackTrace(); 
            JOptionPane.showMessageDialog(null, "Verifique la conexión a la cámara ", "Error al leer la imagen", JOptionPane.ERROR_MESSAGE);
        }
        if (imagen != null) {
            try {
                ImageIO.write(imagen, "png", new File(pathFotos+nombreArchivo+".ppj"));
                 System.out.println(pathFotos+nombreArchivo+".ppj");
            } catch (IOException e) {
                //e.printStackTrace(); 
                JOptionPane.showMessageDialog(null, "No se puede guardar la captura", "Error al guardar la captura", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Verifique la conexión a la cámara ", "Error al accesar a la cámara", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnCamionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamionetaActionPerformed
        // TODO add your handling code here:
        String folio = registro.getFolio();
            registro.setEntrada(folio,"Camioneta", true, false,2,this.hrEntrada);           
        /*String hr = registro.getHrEntrada();
        System.out.println("**************************"+hr);
        guardarFoto("E"+hr.replace(" ","").replace(":","_").replace("-",""), this.FRENTE );*/
        this.opcion = 2;
        this.setVisible(false);
    }//GEN-LAST:event_btnCamionetaActionPerformed

    private void btnHotel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotel1ActionPerformed
        // TODO add your handling code here:
        String folio = registro.getFolio();
            registro.setEntrada(folio,"La.Alhondiga", true, false,3,this.hrEntrada);
        /*String hr = registro.getHrEntrada();
        System.out.println("**************************"+hr);
        guardarFoto("E"+hr.replace(" ","").replace(":","_").replace("-",""), this.FRENTE );*/
        this.opcion = 3;
        this.setVisible(false);
    }//GEN-LAST:event_btnHotel1ActionPerformed

    private void btnHotel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotel2ActionPerformed
        // TODO add your handling code here:
        String folio = registro.getFolio();
            registro.setEntrada(folio,"Puebla.de.Antano", true, false,4,this.hrEntrada);
        /*String hr = registro.getHrEntrada();
        System.out.println("**************************"+hr);
        guardarFoto("E"+hr.replace(" ","").replace(":","_").replace("-",""), this.FRENTE );*/
        this.opcion = 4;
        this.setVisible(false);
    }//GEN-LAST:event_btnHotel2ActionPerformed

    private void btnPensionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPensionadoActionPerformed
        // TODO add your handling code here:
        String folio = registro.getFolio();
            registro.setEntrada(folio,"Pensionado", true, false,5,this.hrEntrada);
        /*String hr = registro.getHrEntrada();
        System.out.println("**************************"+hr);
        guardarFoto("E"+hr.replace(" ","").replace(":","_").replace("-",""), this.FRENTE );*/
        this.opcion = 5;
        this.setVisible(false);
    }//GEN-LAST:event_btnPensionadoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        String folio = registro.getFolio();
        registro.setCancelado("C"+folio,"Cancelado", true, true, 9,this.hrEntrada);
        /*String hr = registro.getHrEntrada();
        System.out.println("**************************"+hr);
        guardarFoto("E"+hr.replace(" ","").replace(":","_").replace("-",""), this.FRENTE );*/
        this.opcion = 0;        
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    public int getRespuesta(){                
        return this.opcion;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               viewEntrada dialog = new viewEntrada(new javax.swing.JFrame(), true,"",true);
               dialog.setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuto;
    private javax.swing.JButton btnCamioneta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnHotel1;
    private javax.swing.JButton btnHotel2;
    private javax.swing.JButton btnPensionado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
