/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.est.views;
import com.est.ctrl.*;
/**
 *
 * @author m
 */
public class viewConfigContrasenas extends javax.swing.JDialog {
usuarioD user = new usuarioD();
    /**
     * Creates new form viewAgregarPensionado
     */
    public viewConfigContrasenas(javax.swing.JDialog parent, boolean modal) {        
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        checkSuper = new javax.swing.JCheckBox();
        checkAdmin = new javax.swing.JCheckBox();
        checkUser = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContrasenaSuper = new javax.swing.JPasswordField();
        txtContrasenaSuperC = new javax.swing.JPasswordField();
        txtContrasenaAdmin = new javax.swing.JPasswordField();
        txtContrasenaAdminC = new javax.swing.JPasswordField();
        txtContrasenaUser = new javax.swing.JPasswordField();
        txtContrasenaUserC = new javax.swing.JPasswordField();
        txtContrasenaAdminCF = new javax.swing.JPasswordField();
        txtContrasenaAdminF = new javax.swing.JPasswordField();
        checkAdminF = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(250, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Configuración");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/config_32.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-32.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error-32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        checkSuper.setText("Super Usuario:");
        checkSuper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkSuper.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkSuperStateChanged(evt);
            }
        });

        checkAdmin.setText("Usuario Administrador:");
        checkAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkAdmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkAdminStateChanged(evt);
            }
        });

        checkUser.setText("Usuario Normal:");
        checkUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkUser.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkUserStateChanged(evt);
            }
        });

        jLabel8.setText("Contraseña Nueva");

        jLabel3.setText("Confirmar Contraseña Nueva");

        txtContrasenaSuper.setEditable(false);

        txtContrasenaSuperC.setEditable(false);

        txtContrasenaAdmin.setEditable(false);

        txtContrasenaAdminC.setEditable(false);

        txtContrasenaUser.setEditable(false);

        txtContrasenaUserC.setEditable(false);

        txtContrasenaAdminCF.setEditable(false);

        txtContrasenaAdminF.setEditable(false);

        checkAdminF.setText("Usuario Administrador F:");
        checkAdminF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkAdminF.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkAdminFStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(checkAdmin)
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(checkSuper)
                                                .addGap(56, 56, 56)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtContrasenaSuper, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                            .addComponent(txtContrasenaAdmin))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtContrasenaSuperC)
                                            .addComponent(txtContrasenaAdminC)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkAdminF)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtContrasenaAdminF)
                                        .addGap(47, 47, 47))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkUser)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtContrasenaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContrasenaUserC, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(txtContrasenaAdminCF)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSuper)
                    .addComponent(txtContrasenaSuper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasenaSuperC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkAdmin)
                    .addComponent(txtContrasenaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasenaAdminC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkAdminF)
                    .addComponent(txtContrasenaAdminF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasenaAdminCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkUser)
                    .addComponent(txtContrasenaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasenaUserC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCancelar))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkSuperStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkSuperStateChanged
        // TODO add your handling code here:
        if(checkSuper.isSelected()){
            txtContrasenaSuper.setEditable(true);
            txtContrasenaSuperC.setEditable(true);
        }
        else{
            txtContrasenaSuper.setEditable(false);
            txtContrasenaSuperC.setEditable(false);
        }
            
    }//GEN-LAST:event_checkSuperStateChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void checkAdminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkAdminStateChanged
        // TODO add your handling code here:
         if(checkAdmin.isSelected()){
            txtContrasenaAdmin.setEditable(true);
            txtContrasenaAdminC.setEditable(true);
        }
        else{
            txtContrasenaAdmin.setEditable(false);
            txtContrasenaAdminC.setEditable(false);
        }
    }//GEN-LAST:event_checkAdminStateChanged

    private void checkUserStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkUserStateChanged
        // TODO add your handling code here:
          if(checkUser.isSelected()){
            txtContrasenaUser.setEditable(true);
            txtContrasenaUserC.setEditable(true);
        }
        else{
            txtContrasenaUser.setEditable(false);
            txtContrasenaUserC.setEditable(false);
        }
    }//GEN-LAST:event_checkUserStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(checkSuper.isSelected() && txtContrasenaSuper.getText().equals(txtContrasenaSuperC.getText())){
            user.setPass(txtContrasenaSuper.getText(), 1);
        }
        if(checkAdmin.isSelected() && txtContrasenaAdmin.getText().equals(txtContrasenaAdminC.getText())){
            user.setPass(txtContrasenaAdmin.getText(), 2);
        }
        if(checkAdminF.isSelected() && txtContrasenaAdminF.getText().equals(txtContrasenaAdminCF.getText())){
            user.setPass(txtContrasenaAdmin.getText(), 4);
        }        
        if(checkUser.isSelected() && txtContrasenaUser.getText().equals(txtContrasenaUserC.getText())){
            user.setPass(txtContrasenaUser.getText(), 3);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkAdminFStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkAdminFStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAdminFStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewConfigContrasenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewConfigContrasenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewConfigContrasenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewConfigContrasenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                viewConfigContrasenas dialog = new viewConfigContrasenas(new javax.swing.JDialog(), true);
                dialog.setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox checkAdmin;
    private javax.swing.JCheckBox checkAdminF;
    private javax.swing.JCheckBox checkSuper;
    private javax.swing.JCheckBox checkUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtContrasenaAdmin;
    private javax.swing.JPasswordField txtContrasenaAdminC;
    private javax.swing.JPasswordField txtContrasenaAdminCF;
    private javax.swing.JPasswordField txtContrasenaAdminF;
    private javax.swing.JPasswordField txtContrasenaSuper;
    private javax.swing.JPasswordField txtContrasenaSuperC;
    private javax.swing.JPasswordField txtContrasenaUser;
    private javax.swing.JPasswordField txtContrasenaUserC;
    // End of variables declaration//GEN-END:variables
}
